### ISSUE TITLE
Feature Request: Search

### ISSUE THREAD

**Issue by JFoxUK** [qwilio/qwil-iframe-api#2]
Ability in app to search conversations (like you can on your web/desktop app) would improve the workflow of the client and improve overall UX.

**Comment by shawnchin** [comment]
ok. will prioritise.

**Comment by shawnchin** [comment]
FYI, this has been added to the current sprint. Watch this space 😁

**Comment by shawnchin** [comment]
This has now been released and should automatically show up in your deployment 🚀
